name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2025-12-18"

[vars]
USERNAME = "$USERNAME"
PASSWORD = "$PASSWORD"
BUCKET_NAME = "$BUCKET_NAME"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "$BUCKET_NAME"
